spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  data:
    rest:
      base-path: /api
      default-media-type: application/json
  hateoas:
    use-hal-as-default-json-media-type: false
  jackson:
    date-format: yyyy-MM-dd

app.cors:
  allowed-origins: >
    "http://localhost:4200"
    "http://localhost:9000"
    "https://user-task-svc.herokuapp.com"